version: "3.7"

services:
  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    ports:
      - "8082:8082"
      - "5013:5013"
      - "5013:5013/udp"
      - "5015:5015"
      - "5015:5015/udp"

    volumes:
      - ${APP_DATA_DIR}/data:/opt/traccar/data
      - ${APP_DATA_DIR}/logs:/opt/traccar/logs
